### ISSUE TITLE
User story: Colour palette and fonts

### ISSUE THREAD

**Issue by sbojorge** [sbojorge/Bill_splitting_0124Hackathon#13]
EPIC #25 
As a **role** I want to **capability** so that  **received benefit**.

## Acceptance criteria
  * Acceptance criteria 1:
  * Acceptance criteria 2:
  * Acceptance criteria 3:

 ## Tasks
 - [ ] Task 1
 - [ ] Taks 2
 - [ ] Task 3

**Comment by MuzhdaN** [comment]
sources:
fonts: https://fonts.google.com/
canva: https://www.canva.com/

**Comment by sbojorge** [comment]
This is the font provided by Sumi on Friday 19/01:
<link rel="preconnect" href="https://fonts.googleapis.com/">
<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=PT+Sans+Narrow&display=swap" rel="stylesheet">

**Comment by sbojorge** [comment]
Done.
