### ISSUE TITLE
User story: Event template

### ISSUE THREAD

**Issue by sbojorge** [sbojorge/Bill_splitting_0124Hackathon#24]
EPIC #
As a **user** I want to **create an event and link it to an expense** so that  **I can begin to split the cost with my partners**.

## Acceptance criteria
  * Acceptance criteria 1:
  * Acceptance criteria 2:
  * Acceptance criteria 3:

 ## Tasks
 - [ ] Task 1
 - [ ] Taks 2
 - [ ] Task 3

**Comment by benschaf** [comment]
pull request #36 should do it

although there is no way to link an event to an expense but i think it should be phrased the other way around: an expense will be linked to an event

**Comment by sbojorge** [comment]
Done.
